spring:
  application:
    name: jpa-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/eclipselink
    username: piomin
    password: piomin123
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      min-pool-size: 5
      max-pool-size: 20
  jpa:
    show-sql: true
    properties:
      eclipselink:
        weaving: true

server:  
  port: ${PORT:8090}