spring:
  application:
    name: jpa-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/eclipselink
    username: piomin
    password: piomin123
    type: oracle.ucp.jdbc.UCPDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      sql-for-validate-connection: select * from dual
      connection-pool-name: connectionPoolName1
      initial-pool-size: 10
      min-pool-size: 5
      max-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:  
  port: ${PORT:8090}